services:
    app:
        container_name: dap_app
        image: dap_frontend_image
        build:
            context: .
            args:
                CONTAINER_PORT: ${CONTAINER_PORT}
        ports:
            - '${HOST_PORT}:${CONTAINER_PORT}'
        env_file:
            - .env
